title: codish_theme
tagline: "This site uses the codish_theme for Jekyll, by Koen Westendorp"
url: "http://yourwebsite.com"

sass:
    sass_dir: css

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

codish_themesite: http://codish_theme.com

permalinks: /:year/:month/:day/:title
